/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASKISI1_H_RPCGEN
#define _ASKISI1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	struct {
		u_int y_len;
		int *y_val;
	} y;
	float a;
};
typedef struct data data;

struct apotelesma {
	struct {
		u_int minmax_len;
		int *minmax_val;
	} minmax;
	struct {
		u_int vec_len;
		float *vec_val;
	} vec;
};
typedef struct apotelesma apotelesma;

#define ASKISI1 0x234511EF
#define ASKISI1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MO 1
extern  float * mo_1(data *, CLIENT *);
extern  float * mo_1_svc(data *, struct svc_req *);
#define MEGEL 2
extern  apotelesma * megel_1(data *, CLIENT *);
extern  apotelesma * megel_1_svc(data *, struct svc_req *);
#define ginom 3
extern  apotelesma * ginom_1(data *, CLIENT *);
extern  apotelesma * ginom_1_svc(data *, struct svc_req *);
extern int askisi1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MO 1
extern  float * mo_1();
extern  float * mo_1_svc();
#define MEGEL 2
extern  apotelesma * megel_1();
extern  apotelesma * megel_1_svc();
#define ginom 3
extern  apotelesma * ginom_1();
extern  apotelesma * ginom_1_svc();
extern int askisi1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_apotelesma (XDR *, apotelesma*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_apotelesma ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASKISI1_H_RPCGEN */
