/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "askisi1.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_apotelesma (XDR *xdrs, apotelesma *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->minmax.minmax_val, (u_int *) &objp->minmax.minmax_len, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->vec.vec_val, (u_int *) &objp->vec.vec_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
